version: '3'

services:
  gqlgen-auth-starter:
    build: .
    volumes:
      - .:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - LOG_FILE=tmp/gqlgen-auth-starter.log