// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/schartey/gqlgen-auth-starter/graphql/resolvers"
	"github.com/schartey/gqlgen-auth-starter/user"
)

// Injectors from wire.go:

func WireUp() *resolvers.RootResolver {
	userService := user.NewUserService()
	rootResolver := resolvers.NewRootResolver(userService)
	return rootResolver
}
